on:
  workflow_call:

jobs:
  comment_diff:
    runs-on: ubuntu-latest

    steps:
      - name: Download caps diff
        id: caps_diff
        continue-on-error: true
        uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 #v4.1.9
        with:
          name: capsdiff

      - if: failure()
        run: |
          echo "No caps diff ✅"

      - id: read_diff
        if: success()
        run: |
          echo "diff=$(base64 --wrap=0 < diff)" > $GITHUB_OUTPUT

      - if: success()
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const content = `
            <details open>
            <summary>
              :warning: New capabilities detected
            </summary>
            ${Buffer.from("${{ steps.read_diff.outputs.diff }}", "base64").toString()}
            </details>
            `
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'COMMENT',
              body: content,
            })
