on:
  push:
  pull_request:

jobs:
  secret_scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Trufflehog

        uses: trufflesecurity/trufflehog@c1f2e912239240108482d79ea01ab25d90b27ac7
